name = "vira"
author = "cirro (snep.lol)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5728b9e8709e2d4796000d2336e25afe9470ae6e8ae50d5e6b9ec57837c04cce"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
