name = "vira"
author = "cirro (snep.lol)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53a69fdaeda49d7aa0da35520495d9ac0d5c860edcf28cfbdea21f68cb612c7a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
