name = "vira"
author = "cirro (snep.lol)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07962d4d14d28091614f50665e2048ff53ad065831cd37e878588bfcf6126a82"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
