name = "vira"
author = "cirro"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13dcc5f37644fd49fa2382b0f4979afef39f2093ae61ff6641baa63ba0d8bb84"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
