name = "vira"
author = "cirro (snep.lol)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e106a353406a612317c39f24ee1e5da62e9eba373f029da28bf4727d9e912ba"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
