name = "vira"
author = "cirro (snep.lol)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bdc25472bebd8bc455458ce58a1ca5dea94c682a1afa3bc9ad11ae02ff5ca13"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
